### ISSUE TITLE
preset default set 'p2' when use nvenc_hevc encoder will get error

### ISSUE THREAD

**Issue by Yshelgi** [chenxinfeng4/ffmpegcv#47]
When i use `hevc` as videowrite encoder and not set `preset`,i get error as pic
![image](https://github.com/user-attachments/assets/ce5647db-5f77-496a-b1ea-246d7eebfe35)

from this error, i track the code and find the default `preset = p2` in `ffmpeg_writer.py`
![image](https://github.com/user-attachments/assets/aac0c616-f4a5-4809-a3c0-f614c4137311)
 
I use `ffmpeg -h encoder=nvenc_hevc` to check `preset`,but 'p2' is not in options
![image](https://github.com/user-attachments/assets/905c15f8-a6a1-417d-935d-d8feff9a9ebb)

In order to solve this problem, either force the `preset` parameter to be set, or modify the default value setting here in the source code.

**Comment by chenxinfeng4** [comment]
I see, and I will figure it out



---- Replied Message ----
| From | ***@***.***> |
| Date | 07/12/2024 14:36 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [chenxinfeng4/ffmpegcv] preset default set 'p2' when use nvenc_hevc encoder will get error (Issue #47) |

When i use hevc as videowrite encoder and not set preset,i get error as pic
image.png (view on web)

from this error, i track the code and find the default preset = p2 in ffmpeg_writer.py
image.png (view on web)

I use ffmpeg -h encoder=nvenc_hevc to check preset,but 'p2' is not in options
image.png (view on web)

In order to solve this problem, either force the preset parameter to be set, or modify the default value setting here in the source code.

**Comment by Yshelgi** [comment]
> I see, and I will figure it out
> […](#)
> ---- Replied Message ---- | From | ***@***.***> | | Date | 07/12/2024 14:36 | | To | ***@***.***> | | Cc | ***@***.***> | | Subject | [chenxinfeng4/ffmpegcv] preset default set 'p2' when use nvenc_hevc encoder will get error (Issue #47) | When i use hevc as videowrite encoder and not set preset,i get error as pic image.png (view on web) from this error, i track the code and find the default preset = p2 in ffmpeg_writer.py image.png (view on web) I use ffmpeg -h encoder=nvenc_hevc to check preset,but 'p2' is not in options image.png (view on web) In order to solve this problem, either force the preset parameter to be set, or modify the default value setting here in the source code. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>


Thank you for your prompt reply, this is probably a small bug. In addition, I would like to ask if there are any good asynchronous reading and writing strategies? I notice `noblock` for capture，but for writer may need use Queue to speed up.

**Comment by chenxinfeng4** [comment]
You probabily get other ffmpeg version installed. The ffmpeg has compatibility issues from v4 to v6.

You can follow this to reinstall the ffmpeg
```
 #1A. LINUX: sudo apt install ffmpeg
 #1B. MAC (No NVIDIA GPU): brew install ffmpeg
 #1C. WINDOWS: download ffmpeg and add to the path
 #1D. CONDA: conda install ffmpeg=6.0.0     #don't use the default 4.x.x version

which ffmpeg #or `where ffmpeg`
ffmpeg -version
 ```

**Comment by chenxinfeng4** [comment]
Yes, `noblock` also support writer.

`ffmpegcv.noblock(ffmpegcv.VideoWriter, *args)`

**Comment by chenxinfeng4** [comment]
Since no more question, this issue will be closed.
